/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UserCardStencil {
        "avatar": string;
        "name": string;
    }
}
declare global {
    interface HTMLUserCardStencilElement extends Components.UserCardStencil, HTMLStencilElement {
    }
    var HTMLUserCardStencilElement: {
        prototype: HTMLUserCardStencilElement;
        new (): HTMLUserCardStencilElement;
    };
    interface HTMLElementTagNameMap {
        "user-card-stencil": HTMLUserCardStencilElement;
    }
}
declare namespace LocalJSX {
    interface UserCardStencil {
        "avatar"?: string;
        "name"?: string;
        "onDeleteStencil"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "user-card-stencil": UserCardStencil;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "user-card-stencil": LocalJSX.UserCardStencil & JSXBase.HTMLAttributes<HTMLUserCardStencilElement>;
        }
    }
}
